# Generated by Django 3.2.9 on 2021-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
