# Generated by Django 3.2.9 on 2021-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_real_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
