# Generated by Django 3.2.9 on 2021-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_template_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='xsl_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
