# Generated by Django 3.2.9 on 2021-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_xsl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
